from pathlib import Path
import json
root=Path('/Users/gaobo/repositories/gitlab/评审项目/bug-go项目标注/0819')
base=root/'2026-08-19'
common={
 'session_id':'','repo_url':'','trajectory':'','gold_patch':'','verify_result':'','harness':'','generator_model':'',
 'go_version':'golang:1.23; go 1.23.0; GOTOOLCHAIN=go1.23.0','repro_determinism':'deterministic',
 'worker':'gaobo','creator':'gaobo','qc_result':'','qc_note':'','sync_feishu':''
}
records={
1:{
'bug_id':'rail-manifest-snapshot-race-001','task_type':'bugfix','bug_category':'concurrency并发问题',
'user_query':'''我们这边调车清单偶尔会自己变，拿到的旧快照过几秒再看，封签号已经跟着新数据走了。并发检查还直接报了这段，代码就在当前目录，麻烦帮我修好。\n==================\nWARNING: DATA RACE\nWrite at 0x00c000106920 by goroutine 8:\n  rail-hazmat-yard-control-service/internal/manifest.(*Store).ReplaceSeal()\n      /Users/gaobo/go-data-work/stack-001-20260819-1128/internal/manifest/store.go:37 +0x1ac\n  rail-hazmat-yard-control-service/internal/manifest.TestManifestConcurrentViewStable.func2()\n      /Users/gaobo/go-data-work/stack-001-20260819-1128/internal/manifest/manifest_test.go:37 +0xf4\n\nPrevious read at 0x00c000106920 by goroutine 7:\n  rail-hazmat-yard-control-service/internal/manifest.TestManifestConcurrentViewStable.func1()\n      /Users/gaobo/go-data-work/stack-001-20260819-1128/internal/manifest/manifest_test.go:30 +0xac''',
'cmds':["go test -race ./internal/manifest -run '^TestManifestSnapshotIsolation$' -count=1","go test -race ./internal/manifest -run '^TestManifestConcurrentViewStable$' -count=1","go test -race ./internal/manifest -run '^TestManifestRevisionMatchesPublishedView$' -count=1"],
'root':'文件: internal/manifest/store.go, internal/manifest/snapshot.go, internal/manifest/service.go 符号: Store.Snapshot, View.Clone, Service.Refresh 机制: 内部可变切片和缓存视图被直接共享给并发读取者，写入会污染历史快照并造成 data race，发布字段也可能来自不同 revision。',
'criteria':'1. 同一份历史调车清单在后续换封签后内容仍保持原样；2. 并发读写清单连续20轮都不再出现竞态或旧视图串改；3. 每次发布的车辆数、危化数量和 revision 始终属于同一版本；4. 撤回任一层的快照复制或原子发布处理后，对应定向检查重新变红；5. 项目全量回归无新增失败。',
'claims':[('history_snapshot_detached','换封签不能改写已返回的历史清单','TestManifestSnapshotIsolation',['internal/manifest/store.go','internal/manifest/snapshot.go']),('concurrent_view_race_free','并发更新期间已发布视图不与写入共享存储','TestManifestConcurrentViewStable',['internal/manifest/store.go','internal/manifest/snapshot.go']),('revision_view_atomic','revision 与视图统计按同一版本发布','TestManifestRevisionMatchesPublishedView',['internal/manifest/service.go','internal/manifest/snapshot.go'])]},
2:{'bug_id':'rail-inspection-early-completion-002','task_type':'bugfix','bug_category':'concurrency并发问题','user_query':'三组车辆检查一起跑时，只要最快那组先结束，汇总就提前返回了，慢一点的结果和故障信息都没了。这个服务今天要联调，当前目录可以直接用，帮我把并发检查修好。','cmds':["go test -race ./internal/inspection -run '^TestInspectionWaitsForEveryWorker$' -count=1","go test -race ./internal/inspection -run '^TestInspectionCollectsWorkerErrors$' -count=1","go test -race ./internal/inspection -run '^TestInspectionStreamClosesAfterResults$' -count=1"],'root':'文件: internal/inspection/worker_pool.go, internal/inspection/result_sink.go, internal/inspection/coordinator.go 符号: Inspector.Inspect, Sink.Snapshot, Coordinator.Run 机制: worker 完成计数、错误收集和结果流关闭没有统一生命周期，首个 goroutine 返回后就提前发布完成，造成结果丢失和 channel 时序错位。','criteria':'1. 快任务先结束时汇总仍会等待其余检查员全部完成；2. 两个检查员同时失败时两条错误都能保留下来；3. 流式结果在最后一条检查结果送达后才关闭；4. 三条并发场景各连续20轮保持稳定；5. 移除等待、错误归集或关闭时序中的任一修复后对应测试再次失败，且全量回归通过。','claims':[('wait_all_inspectors','汇总必须等待全部检查 worker','TestInspectionWaitsForEveryWorker',['internal/inspection/coordinator.go','internal/inspection/worker_pool.go']),('collect_all_failures','并发失败都进入错误集合','TestInspectionCollectsWorkerErrors',['internal/inspection/result_sink.go','internal/inspection/coordinator.go']),('stream_close_after_results','结果流在所有 worker 完成后关闭','TestInspectionStreamClosesAfterResults',['internal/inspection/coordinator.go','internal/inspection/result_sink.go'])]},
3:{'bug_id':'rail-permit-error-chain-break-003','task_type':'diagnosis','bug_category':'error异常错误','user_query':'铁路授权端明明回的是拒绝，服务却又重试了好几次，最后还统一成了 500；繁忙状态也没标成可重试。文件先不要改，帮我查清楚这几种错误为什么穿过几层以后认不出来。','cmds':["go test ./internal/permit -run '^TestPermitPreservesSentinelChain$' -count=1","go test ./internal/permit -run '^TestPermitDoesNotRetryUnauthorized$' -count=1","go test ./internal/permit -run '^TestPermitMapsBusyDependency$' -count=1"],'root':'文件: internal/permit/gateway.go, internal/permit/retry.go, internal/permit/mapper.go 符号: callGateway, Service.Issue, MapError 机制: 网关层用 %v 把 sentinel 错误格式化成普通文本，重试层无法通过 errors.Is 分类，映射层再按完整字符串比较，错误链断裂后拒绝被重试且繁忙被误映射。','criteria':'1. 实际复现拒绝错误的 sentinel 链丢失；2. 记录未授权请求被重复调用的次数；3. 说明繁忙依赖为何落到普通 500；4. 结论必须落到三个具体文件和对应符号，并串起错误传播链；5. 全程不得改任何代码或测试文件。','claims':[('sentinel_chain_preserved','拒绝错误应保留 sentinel 身份','TestPermitPreservesSentinelChain',['internal/permit/gateway.go']),('unauthorized_not_retried','未授权错误不能进入重试循环','TestPermitDoesNotRetryUnauthorized',['internal/permit/retry.go']),('busy_maps_retryable','繁忙依赖应映射为可重试服务错误','TestPermitMapsBusyDependency',['internal/permit/mapper.go','internal/permit/gateway.go'])]},
4:{'bug_id':'rail-telemetry-typed-nil-panic-004','task_type':'bugfix','bug_category':'nil相关问题','user_query':'''遥测服务用默认配置启动后，一注册温度解码器就崩了；另一个环境传了空实现，居然还被当成可用对象。我把现场栈贴下面，工程已经放好了，帮我把崩溃和空实现识别一起处理掉。\n--- FAIL: TestTelemetryZeroRegistryCanRegister (0.00s)\npanic: assignment to entry in nil map [recovered, repanicked]\n\ngoroutine 6 [running]:\ntesting.tRunner.func1.2({0x100965de0, 0x100a788c0})\n\t/opt/homebrew/Cellar/go/1.25.1/libexec/src/testing/testing.go:1872 +0x190\npanic({0x100965de0?, 0x100a788c0?})\n\t/opt/homebrew/Cellar/go/1.25.1/libexec/src/runtime/panic.go:783 +0x120\nrail-hazmat-yard-control-service/internal/telemetry.(*Registry).Register(0x1400006e240, {0x10090f57c, 0x4}, {0x10098f2a0, 0x100aa90e0})\n\t/Users/gaobo/go-data-work/stack-004-20260819-1128/internal/telemetry/registry.go:15 +0x74\nrail-hazmat-yard-control-service/internal/telemetry.TestTelemetryZeroRegistryCanRegister(0x140000036c0)\n\t/Users/gaobo/go-data-work/stack-004-20260819-1128/internal/telemetry/telemetry_test.go:24 +0x4c''','cmds':["go test ./internal/telemetry -run '^TestTelemetryZeroRegistryCanRegister$' -count=1","go test ./internal/telemetry -run '^TestTelemetryRejectsTypedNilDecoder$' -count=1","go test ./internal/telemetry -run '^TestTelemetryValidationCannotBeBypassed$' -count=1"],'root':'文件: internal/telemetry/registry.go, internal/telemetry/validator.go, internal/telemetry/ingest.go 符号: Registry.Register, isNilDecoder, Ingestor.Ingest 机制: 零值 Registry 向 nil map 写入触发 panic，接口中的 typed nil 又绕过普通 nil 比较，解码器可能被调用崩溃，校验器分支还会把非 nil 校验器跳过。','criteria':'1. Registry 零值直接注册解码器不再 panic；2. 装入接口的 typed nil decoder 会被拒绝且不会进入调用；3. 有效校验器返回的错误仍沿链路上抛，坏数据不落入 accepted；4. 三个场景各连续20轮结果一致；5. 撤回 map 初始化、typed nil 判断或校验调用任一处理后对应测试变红，并保持全量回归通过。','claims':[('zero_registry_initializes_map','零值注册表注册时初始化内部 map','TestTelemetryZeroRegistryCanRegister',['internal/telemetry/registry.go']),('typed_nil_decoder_rejected','接口中的 typed nil decoder 不得暴露','TestTelemetryRejectsTypedNilDecoder',['internal/telemetry/registry.go','internal/telemetry/validator.go']),('validator_always_applied','有效 validator 必须执行且阻止坏读数落库','TestTelemetryValidationCannotBeBypassed',['internal/telemetry/ingest.go','internal/telemetry/validator.go'])]},
5:{'bug_id':'rail-clearance-context-contamination-005','task_type':'diagnosis','bug_category':'context相关问题','user_query':'清场校验有时超时了还一直等，先来一个取消请求后，下一笔正常请求又马上报 canceled。先别动文件，麻烦把这两个看着相反的现象查到同一条调用链上。','cmds':["go test ./internal/clearance -run '^TestClearanceDeadlineReachesVerifier$' -count=1","go test ./internal/clearance -run '^TestClearanceRequestsDoNotShareContext$' -count=1","go test ./internal/clearance -run '^TestClearanceRetryStopsAfterCancellation$' -count=1"],'root':'文件: internal/clearance/repository.go, internal/clearance/worker.go, internal/clearance/pipeline.go 符号: Repository.Save, verifyWithRetry, Pipeline.Clear 机制: Pipeline 用 Background 截断 deadline，Repository 把首个请求 context 缓存在结构体复用，重试循环不检查 ctx.Err，导致取消传播断点与旧 context 状态污染同时存在。','criteria':'1. 复现 verifier 收不到 deadline 而继续等待；2. 复现取消请求污染下一笔正常保存；3. 确认取消前重试仍发生额外调用；4. 定位说明必须包含文件、符号和 context 生命周期如何跨层错位；5. 排查期间不能产生代码差异。','claims':[('deadline_reaches_verifier','请求 deadline 必须传到 verifier','TestClearanceDeadlineReachesVerifier',['internal/clearance/pipeline.go']),('request_context_isolated','仓储不能复用上一请求 context','TestClearanceRequestsDoNotShareContext',['internal/clearance/repository.go','internal/clearance/pipeline.go']),('retry_observes_cancel','已取消 context 不得继续调用 verifier','TestClearanceRetryStopsAfterCancellation',['internal/clearance/worker.go','internal/clearance/pipeline.go'])]},
6:{'bug_id':'rail-consist-slice-aliasing-006','task_type':'bugfix','bug_category':'slice相关问题','user_query':'危化车筛选完以后，原车列顺序被改了；再给路由结果改股道，历史计划也跟着变。这个串数据已经影响编组复核了，代码都在当前目录，请帮我修好。','cmds':["go test ./internal/consist -run '^TestConsistFilteringDoesNotMutateInput$' -count=1","go test ./internal/consist -run '^TestConsistPlanSlicesAreIndependent$' -count=1","go test ./internal/consist -run '^TestConsistReservationReturnsDetachedPlan$' -count=1"],'root':'文件: internal/consist/normalize.go, internal/consist/planner.go, internal/consist/reservation.go 符号: HazardOnly, BuildPlan, ReservationBook.Save 机制: 过滤使用 s[:0] 原地压缩，路由修改和计划存储继续共享底层数组，输入切片、多个视图与仓储快照发生别名污染。','criteria':'1. 危化筛选后传入的完整车列内容和顺序不变；2. 改写 routed 里的车辆不会影响 original 或 hazard；3. 修改 Load 返回的计划不能污染 ReservationBook 内部记录；4. 三条独立性检查连续20轮稳定；5. 移除任一复制边界后对应测试重新失败，项目全量回归仍为绿色。','claims':[('filter_keeps_input','过滤不能原地覆盖输入车列','TestConsistFilteringDoesNotMutateInput',['internal/consist/normalize.go']),('plan_views_independent','计划中的三个切片视图互不共享底层数组','TestConsistPlanSlicesAreIndependent',['internal/consist/normalize.go','internal/consist/planner.go']),('reservation_snapshot_detached','保存和读取计划都要隔离切片所有权','TestConsistReservationReturnsDetachedPlan',['internal/consist/reservation.go','internal/consist/planner.go'])]},
7:{'bug_id':'rail-incident-defer-transaction-leak-007','task_type':'bugfix','bug_category':'defer相关问题','user_query':'事故批处理到第三项就提示资源上限，校验失败时返回值还是空的，提交失败后事务也没回滚。现场比较急，你直接在当前项目里帮我把这套资源和事务处理修好。','cmds':["go test ./internal/incident -run '^TestIncidentBatchReleasesEachResource$' -count=1","go test ./internal/incident -run '^TestIncidentBusinessErrorSurvivesCleanup$' -count=1","go test ./internal/incident -run '^TestIncidentCommitFailureRollsBack$' -count=1"],'root':'文件: internal/incident/transaction.go, internal/incident/batch.go, internal/incident/service.go 符号: Tx.Commit, ProcessBatch, Service.Record 机制: 循环体 defer 到函数尾才释放资源，命名返回值又被 defer 中的 Commit 结果覆盖，提交错误还先标记 committed 使 Rollback 失效。','criteria':'1. 批量数量超过资源上限时每一项完成后都立即归还句柄；2. 校验错误保持 errors.Is 可识别且事务只处于 rolled back；3. Commit 失败也必须回滚并保留提交错误；4. 三种失败路径连续20轮状态一致；5. 回退资源作用域、错误保留或事务状态修复中的任一项后定向检查变红，全量回归不受影响。','claims':[('batch_resource_scope','每个批次项结束即释放资源','TestIncidentBatchReleasesEachResource',['internal/incident/batch.go']),('business_error_not_overwritten','清理和提交不得覆盖已有业务错误','TestIncidentBusinessErrorSurvivesCleanup',['internal/incident/service.go','internal/incident/transaction.go']),('commit_failure_rolls_back','提交失败后事务状态必须回滚','TestIncidentCommitFailureRollsBack',['internal/incident/service.go','internal/incident/transaction.go'])]},
8:{'bug_id':'rail-dispatch-retry-state-desync-008','task_type':'diagnosis','bug_category':'其他问题','user_query':'被 hold 的调车任务重试成功后还停在 moving，有时候 retrying 任务在进行中列表里也找不到，尝试次数还多加了一次。不要修改代码，帮我顺着完整状态流转查清楚。','cmds':["go test ./internal/dispatch -run '^TestDispatchRetryCanComplete$' -count=1","go test ./internal/dispatch -run '^TestDispatchRetryingIsVisibleInProgress$' -count=1","go test ./internal/dispatch -run '^TestDispatchRecoveryIncrementsAttemptsOnce$' -count=1"],'root':'文件: internal/dispatch/state.go, internal/dispatch/service.go, internal/dispatch/worker.go, internal/dispatch/query.go 符号: CanTransition, Service.Move, Worker.Recover, IsInProgress 机制: retrying 中间态在转换表、worker 终态写回、查询可见集合和尝试计数之间未同步，跨包状态机错位使恢复链停在 moving、列表漏项并重复计数。','criteria':'1. 实际驱动 held 到 retrying 再恢复的链路并看到终态错误；2. 单独复现 retrying 在进行中查询中消失；3. 记录一次恢复为何累计两次 attempts；4. 结论要落到四个文件及符号并说明状态机协同缺口；5. 全程不得写入源码或测试。','claims':[('retry_reaches_completed','恢复链必须从 held 走到 completed','TestDispatchRetryCanComplete',['internal/dispatch/state.go','internal/dispatch/worker.go']),('retry_visible_in_progress','retrying 中间态应在进行中查询可见','TestDispatchRetryingIsVisibleInProgress',['internal/dispatch/query.go']),('attempt_count_once','一次恢复只增加一次 attempts','TestDispatchRecoveryIncrementsAttemptsOnce',['internal/dispatch/service.go','internal/dispatch/worker.go'])]},
9:{'bug_id':'rail-occupancy-map-publication-race-009','task_type':'bugfix','bug_category':'concurrency并发问题','user_query':'股道占用快照返回后，调用方删一个键居然把台账也删了；并发预留时视图里的版本号还经常少一拍，整条移车会跳两个版本。当前目录就是现场代码，帮我把这组并发状态问题修好。','cmds':["go test -race ./internal/occupancy -run '^TestOccupancySnapshotDetached$' -count=1","go test -race ./internal/occupancy -run '^TestOccupancyConcurrentViewsAreConsistent$' -count=1","go test -race ./internal/occupancy -run '^TestOccupancyMovePublishesSingleRevision$' -count=1"],'root':'文件: internal/occupancy/ledger.go, internal/occupancy/allocator.go, internal/occupancy/observer.go 符号: Ledger.Snapshot, Allocator.Move, Observe 机制: Ledger 把内部 map 直接返回并把错误 revision 分开发布，Move 又用 Release 和 Reserve 两次锁事务，外部修改、并发迭代和中间状态都会造成竞态与撕裂快照。','criteria':'1. 修改 Snapshot 返回的 map 不会改变 Ledger 内部占用；2. 并发预留和观察连续20轮都没有 map 竞态或统计撕裂；3. 一次移车只发布一个新 revision，外部看不到空窗状态；4. 去掉 map 复制、同锁移动或同版本观察中的任一修复后对应目标检查重新变红；5. 全量回归全部通过。','claims':[('snapshot_map_detached','返回的占用 map 与内部台账隔离','TestOccupancySnapshotDetached',['internal/occupancy/ledger.go','internal/occupancy/observer.go']),('concurrent_observation_consistent','并发写入时观察视图无竞态且统计一致','TestOccupancyConcurrentViewsAreConsistent',['internal/occupancy/ledger.go','internal/occupancy/observer.go']),('move_single_revision','移车在同一临界区只推进一次版本','TestOccupancyMovePublishesSingleRevision',['internal/occupancy/ledger.go','internal/occupancy/allocator.go'])]},
10:{'bug_id':'rail-audit-cancel-checkpoint-order-010','task_type':'diagnosis','bug_category':'context相关问题','user_query':'审计流超时后 source 还在等，投递失败的那条却已经把 checkpoint 往前推了；首条事件取消后也继续拉了十次。先别改代码，帮我把取消和位点提交的先后关系查明白。','cmds':["go test ./internal/audit -run '^TestAuditCancellationReachesSource$' -count=1","go test ./internal/audit -run '^TestAuditFailedDeliveryDoesNotAdvanceCheckpoint$' -count=1","go test ./internal/audit -run '^TestAuditStopsReadingAfterCancel$' -count=1"],'root':'文件: internal/audit/checkpoint.go, internal/audit/subscriber.go, internal/audit/stream.go 符号: Checkpoint.Commit, Source.Next, Stream.Run 机制: Source 和 Sink 被强制换成 Background context，循环不检查取消，而且 checkpoint 在 Deliver 成功前提交，导致取消传播断裂、失败事件被越过和残留读取继续执行。','criteria':'1. 复现 deadline 无法打断 source 等待；2. 复现 sink 失败后 checkpoint 仍前进；3. 取消发生后确认 source 被继续读取多次；4. 定位结果必须包含三个文件、符号及 context 与 checkpoint 的时序关系；5. 文件不得改动，排查结束后工作区零差异。','claims':[('source_observes_cancel','source 调用必须接收请求取消','TestAuditCancellationReachesSource',['internal/audit/subscriber.go','internal/audit/stream.go']),('checkpoint_after_delivery','投递失败不能推进 checkpoint','TestAuditFailedDeliveryDoesNotAdvanceCheckpoint',['internal/audit/checkpoint.go','internal/audit/stream.go']),('loop_stops_on_cancel','取消后循环不再读取下一事件','TestAuditStopsReadingAfterCancel',['internal/audit/stream.go','internal/audit/subscriber.go'])]}
}
for n,d in records.items():
 rec=f'rail-hazmat-yard-control-service__{n:03d}'
 data=dict(common); data.update({k:v for k,v in d.items() if k not in ('cmds','root','criteria','claims')})
 data['sample_id']=str(20260819000+n)
 data['verify_cmds']='\n'.join(d['cmds'])
 data['gold_root_cause']=d['root']
 data['success_criteria']=d['criteria']
 claims=[]
 for idx,(cid,desc,test,paths) in enumerate(d['claims']):
  claims.append({'id':cid,'description':desc,'test':test,'command':d['cmds'][idx],'paths':paths})
 data['coverage_contract']={'version':1,'claims':claims}
 p=base/rec
 (p/'prompt.txt').write_text(d['user_query'].strip()+'\n')
 (p/'draft_collection.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
